### ISSUE TITLE
Support for Android < 5.0

### ISSUE THREAD

**Issue by brandall76** [GoogleCloudPlatform/android-docs-samples#5]
The demo will fail for Android devices running < 5.0 due to the missing security provider update:

`ProviderInstaller.installIfNeeded(mContext);`

[Doc link](https://developer.android.com/training/articles/security-gms-provider.html#example_sync).

A check for a successful response would be needed prior to anything else initialising, otherwise it will throw a TRANSIENT_FAILURE

Ben

**Comment by yaraki** [comment]
Neither Speech nor NaturalLanguage samples uses that method, and they are working fine on older devices.
