### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by brandall76** [GoogleCloudPlatform/android-docs-samples#6]
The call:

`mApi = SpeechGrpc.newStub(channel);` [link](https://github.com/GoogleCloudPlatform/android-docs-samples/blob/master/speech/Speech/app/src/main/java/com/google/cloud/android/speech/ApiFragment.java#L174)

Often takes over 1 second to return, longer with network latency.

If the voice recorder initialises prior to this and calls `onVoiceStart()` [link](https://github.com/GoogleCloudPlatform/android-docs-samples/blob/master/speech/Speech/app/src/main/java/com/google/cloud/android/speech/MainActivity.java#L61)

`startRecognizing()` will return immediately, [causing the request observer to remain null](https://github.com/GoogleCloudPlatform/android-docs-samples/blob/master/speech/Speech/app/src/main/java/com/google/cloud/android/speech/ApiFragment.java#L182)

Subsequent calls will fail.

Ben

**Comment by yaraki** [comment]
Yes, mApi can be null there and that's why we are null-checking there.
